### ISSUE TITLE
No podspec found for `flutter_open_app_settings` in `.symlinks/plugins/flutter_open_app_settings/ios`

### ISSUE THREAD

**Issue by IluhinDotPro** [josephcrowell/flutter_open_app_settings#1]
**What version of this package are you using?**
flutter_open_app_settings: ^0.1.3

**What operating system, Node.js, and npm version?**
MacOS

**What happened?**
Can't run `pod install`

**What did you expect to happen?**
```
Generating Pods project
Integrating client project
Pod installation complete! There are 12 dependencies from the Podfile and 12 total pods installed.
```

**Are you willing to submit a pull request to fix this bug?**
**FIX:** Just rename `flutter_open_app_settings/ios/open_apps_settings.podspec` to `flutter_open_app_settings/ios/flutter_open_app_settings.podspec`

**Comment by josephcrowell** [comment]
Fixed in v 0.1.4 just pushed to pub.dev
