### ISSUE TITLE
Package doesn't support minSdkVersion 21

### ISSUE THREAD

**Issue by xOldeVx** [josephcrowell/flutter_open_app_settings#2]
The `minSdkVersion` of the package is `28`, It's very heigh, most of the packages supports `minSdkVersion 21`, is it possible to fix it?

**Comment by josephcrowell** [comment]
No some of the dialogue open calls don't work on versions below 28.

I believe there is another package that is compatible with Android versions below 28 (down to 21) but it is broken on newer Android versions.

You may be able to make some of the dialogues (definitely not all of them) work with deprecation checks on versions that old but it's not something that I needed. I don't need to target the 5% of active devices that might still be operational on SDK versions that old. If you decide to do the deprecation checks and modify this code for compatibility with those old SDK versions, I encourage you to do a pull request.
